name: cuda-env
# default /user-environment
#store: /user-environment
spack:
    repo: https://github.com/spack/spack.git
    commit: 6408b51
    packages:
      repo: https://github.com/spack/spack-packages.git
      commit: develop
#mirror:
    # default None
    #key: None
    # default True
    #enable: True
# default True
#modules: True
version: 2
