name: cuda-env
store: /alternative-point
spack:
    repo: https://github.com/spack/spack.git
    commit: 6408b51
    packages:
        repo: https://github.com/spack/spack-packages.git
        commit: develop
mirror:
    key: /home/bob/veryprivate.key
    enable: True
modules: False
description: "a really useful environment"
version: 2
