full-env:
  compiler: [gcc]
  unify: when_possible
  specs:
  - osu-micro-benchmarks@5.9
  - hdf5 +mpi
  network:
    mpi: cray-mpich +cuda
  packages:
  - perl
  - git
  variants:
  - +mpi
  - +cuda
  # expect an error because 'providers' is not defined in schema.
  providers:
    libglx: [opengl]
