#!/usr/bin/python3

import os
import os.path
import sys

# Find this tool's location and prefix.
tool_file = os.path.realpath(os.path.expanduser(__file__))
tool_prefix = os.path.dirname(tool_file)

tool_lib_path = os.path.join(tool_prefix, "lib")
sys.path.insert(0, tool_lib_path)

external_lib_path = os.path.join(tool_lib_path, "external")
sys.path.insert(0, external_lib_path)

import sstool.main

# Once we've set up the system path, run the tool's main method
if __name__ == "__main__":
    sys.exit(sstool.main.main(tool_prefix))

