name: cuda-env
store: /user-environment
spack:
    repo: https://github.com/spack/spack.git
    commit: 6408b51
    packages:
        repo: https://github.com/spack/spack-packages.git
mirror:
    enable: false
version: 2
