gcc-env:
  compiler: [gcc]
  unify: true
  specs:
  - cuda@11.8
  - osu-micro-benchmarks@5.9
  network:
    mpi: cray-mpich+cuda
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
tools:
  compiler: [gcc]
  unify: true
  specs:
  - cmake
  - python@3.10
