#!/bin/bash

echo "====================================="
echo "=====     post install hook     ====="

mount_path={{ env.mount }}
echo RUNNING IN $mount_path

echo
echo "=====   environment variabls    ====="
printenv

echo
echo "=====   create post file {{ env.mount }}/post  ====="
echo "$(date)" > "$mount_path/post"

echo
echo "===== list all spack packages ====="
spack -C {{ env.config }} find

echo "====================================="
